services:
  - type: web
    name: labocq
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
